# Global Agent Configuration
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000

# -----------------------------------------------------------------------------
# INPUT: Listen to your local MQTT Broker (or TTN in Prod)
# -----------------------------------------------------------------------------
[[inputs.mqtt_consumer]]
  # In PROD, you change this to TTN: servers = ["tcps://eu1.cloud.thethings.network:8883"]
  servers = ["$MQTT_BROKER_URL"]

  # The topic TTN uses for uplinks
  topics = ["v3/parking/devices/master/up"]

  # We expect the payload to be JSON format
  data_format = "json"

  # Treat all JSON fields as data points
  json_strict = true

# -----------------------------------------------------------------------------
# OUTPUT: Send the parsed data to InfluxDB
# -----------------------------------------------------------------------------
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]

  # These MUST match the environment variables in your docker-compose.yml
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"